spring:

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth-service  # 인증 서비스로 라우팅
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**  # 로그인 및 회원 가입 경로
        - id: review-service
          uri: http://localhost:8082
          predicates:
            - Path=/review/**
        - id: sns-service
          uri: http://localhost:8083
          predicates:
            - Path=/sns/**

  application:
    name: gateway

server:
  port: 8080  # Gateway의 포트
